name: "Test the action"
on:
  push:
    branches: [ master ]

jobs:
  
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Get Version
      uses: ./
      id: get_version
      with:
        PROJ_PATH: ./.github/workflows/Project.csproj
        
    - name: Get Version 1
      uses: ./
      id: get_version1
      with:
        PROJ_PATH: ./.github/workflows/Project.csproj
        VER_PLACES : 1

    - name: Get Version 2
      uses: ./
      id: get_version2
      with:
        PROJ_PATH: ./.github/workflows/Project.csproj
        VER_PLACES : 2

    - name: Get Version 3
      uses: ./
      id: get_version3
      with:
        PROJ_PATH: ./.github/workflows/Project.csproj
        VER_PLACES : 3
        
    - name: Get Version 4
      uses: ./
      id: get_version4
      with:
        PROJ_PATH: ./.github/workflows/Project.csproj
        VER_PLACES : 4
